/*
SQL code is taken from the Java SE tutorial and licensed under
http://www.oracle.com/technetwork/licenses/bsd-license-1835287.html .
*/
# --- !Ups
create table companies ("id" INTEGER NOT NULL,"name" VARCHAR NOT NULL);
create table computers ("id" INTEGER NOT NULL,"name" VARCHAR NOT NULL,"manufacturer_id" INTEGER NOT NULL);

insert into companies values (1,'apple inc.');
insert into companies values (2,'thinking machines');
insert into companies values (3,'rca');
insert into companies values (4,'netronics');
insert into companies values (5,'tandy corporation');
insert into companies values (6,'commodore international');
insert into companies values (7,'mos technology');
insert into companies values (8,'micro instrumentation and telemetry systems');
insert into companies values (9,'ims associates,  inc.');
insert into companies values (10,'digital equipment corporation');
insert into companies values (11,'lincoln laboratory');
insert into companies values (12,'moore school of electrical engineering');
insert into companies values (13,'ibm');
insert into companies values (14,'amiga corporation');
insert into companies values (15,'canon');
insert into companies values (16,'nokia');
insert into companies values (17,'sony');
insert into companies values (18,'oqo');
insert into companies values (19,'next');
insert into companies values (20,'atari');
insert into companies values (21,'acorn computersrow');
insert into companies values (22,'timex sinclair');
insert into companies values (23,'nintendo');
insert into companies values (24,'sinclair research ltd');
insert into companies values (25,'xerox');
insert into companies values (26,'hewlett-packard');
insert into companies values (27,'zemmix');
insert into companies values (28,'acvs');
insert into companies values (29,'sanyo');
insert into companies values (30,'cray');
insert into companies values (31,'evans & sutherland');
insert into companies values (32,'e.s.r. inc.');
insert into companies values (33,'omron');
insert into companies values (34,'bbn technologies');
insert into companies values (35,'lenovo group');
insert into companies values (36,'asus');
insert into companies values (37,'amstrad');
insert into companies values (38,'sun microsystems');
insert into companies values (39,'texas instruments');
insert into companies values (40,'htc corporation');
insert into companies values (41,'research in motion');
insert into companies values (42,'Samsung Electronics');

insert into computers values (1,'macbook pro 15.4 inch', 1);
insert into computers values (2,'cm-2a', 2);
insert into computers values (3,'cm-200', 2);
insert into computers values (4,'cm-5e', 2);
insert into computers values (5,'cm-5', 2);
insert into computers values (6,'macbook pro', 1);
insert into computers values (7,'apple iie', 1);
insert into computers values (8,'apple iic', 1);
insert into computers values (9,'apple iigs', 1);
insert into computers values (10,'apple iic plus', 1);
insert into computers values (11,'apple ii plus', 1);
insert into computers values (12,'apple iii', 1);
insert into computers values (13,'apple lisa', 1);
insert into computers values (14,'cm-2', 2);
insert into computers values (15,'connection machine', 2);
insert into computers values (16,'apple ii', 1);
insert into computers values (17,'apple iii plus', 1);
insert into computers values (18,'cosmac elf', 3);
insert into computers values (19,'cosmac vip', 3);
insert into computers values (20,'elf ii', 4);
insert into computers values (21,'macintosh', 1);
insert into computers values (22,'macintosh ii', 0);
insert into computers values (23,'macintosh plus', 1);
insert into computers values (24,'macintosh iifx', 0);
insert into computers values (25,'imac', 1);
insert into computers values (26,'mac mini', 1);
insert into computers values (27,'mac pro', 1);
insert into computers values (28,'power macintosh', 1);
insert into computers values (29,'powerbook', 1);
insert into computers values (30,'xserve', 0);
insert into computers values (31,'powerbook 100', 0);
insert into computers values (32,'powerbook 140', 0);
insert into computers values (33,'powerbook 170', 0);
insert into computers values (34,'powerbook duo', 0);
insert into computers values (35,'powerbook 190', 0);
insert into computers values (36,'macintosh quadra', 1);
insert into computers values (37,'macintosh quadra 900', 0);
insert into computers values (38,'macintosh quadra 700', 0);
insert into computers values (39,'macintosh lc', 1);
insert into computers values (40,'macintosh lc ii', 1);
insert into computers values (41,'macintosh lc iii', 1);
insert into computers values (42,'macintosh lc iii+', 0);
insert into computers values (43,'macintosh quadra 605', 1);
insert into computers values (44,'macintosh lc 500 series', 0);
insert into computers values (45,'trs-80 color computersrow', 5);
insert into computers values (46,'acorn system 2', 0);
insert into computers values (47,'dragon 32/64', 0);
insert into computers values (48,'mek6800d2', 0);
insert into computers values (49,'newbear 77/68', 0);
insert into computers values (50,'commodore pet', 6);
insert into computers values (51,'commodore 64', 6);
insert into computers values (52,'commodore 64c', 0);
insert into computers values (53,'commodore sx-64', 6);
insert into computers values (54,'commodore 128', 6);
insert into computers values (55,'apple i', 1);
insert into computers values (56,'kim-1', 7);
insert into computers values (57,'altair 8800', 8);
insert into computers values (58,'imsai 8080', 9);
insert into computers values (59,'imsai series two', 0);
insert into computers values (60,'vax', 10);
insert into computers values (61,'vax 11/780', 10);
insert into computers values (62,'vax 11/750', 10);
insert into computers values (63,'tx-2', 11);
insert into computers values (64,'tx-0', 11);
insert into computers values (65,'whirlwind', 11);
insert into computers values (66,'eniac', 12);
insert into computers values (67,'ibm pc', 13);
insert into computers values (68,'macintosh classic', 0);
insert into computers values (69,'macintosh classic ii', 1);
insert into computers values (70,'amiga', 14);
insert into computers values (71,'amiga 1000', 6);
insert into computers values (72,'amiga 500', 6);
insert into computers values (73,'amiga 500+', 0);
insert into computers values (74,'amiga 2000', 6);
insert into computers values (75,'amiga 3000', 6);
insert into computers values (76,'amiga 600', 6);
insert into computers values (77,'macintosh 128k', 1);
insert into computers values (78,'macintosh 512k', 1);
insert into computers values (79,'macintosh se', 1);
insert into computers values (80,'macintosh se/30', 1);
insert into computers values (81,'canon cat', 15);
insert into computers values (82,'nokia 770', 16);
insert into computers values (83,'nokia n800', 16);
insert into computers values (84,'mylo', 17);
insert into computers values (85,'oqo 02', 18);
insert into computers values (86,'oqo 01+', 0);
insert into computers values (87,'pinwheel calculator', 0);
insert into computers values (88,'ibook', 1);
insert into computers values (89,'macbook', 1);
insert into computers values (90,'nextstation', 19);
insert into computers values (91,'nextcube', 19);
insert into computers values (92,'nextstation color turbo', 0);
insert into computers values (93,'nextstation color', 0);
insert into computers values (94,'nextstation turbo', 0);
insert into computers values (95,'nextcube turbo', 19);
insert into computers values (96,'nextcube 040', 19);
insert into computers values (97,'nextcube 030', 19);
insert into computers values (98,'tinkertoy tic-tac-toe computersrow', 0);
insert into computers values (99,'z3', 0);
insert into computers values (100,'z4', 0);
insert into computers values (101,'z1', 0);
insert into computers values (102,'z2', 0);
insert into computers values (103,'wang 2200', 0);
insert into computers values (104,'wang vs', 0);
insert into computers values (105,'wang ois', 0);
insert into computers values (106,'bbc micro', 22);
insert into computers values (107,'ibm 650', 13);
insert into computers values (108,'cray-1', 0);
insert into computers values (109,'cray-3', 0);
insert into computers values (110,'cray-2', 0);
insert into computers values (111,'cray-4', 0);
insert into computers values (112,'cray x1', 0);
insert into computers values (113,'cray xd1', 0);
insert into computers values (114,'cray t3d', 0);
insert into computers values (115,'cray t3e', 0);
insert into computers values (116,'cray c90', 0);
insert into computers values (117,'cray t90', 0);
insert into computers values (118,'cray sv1', 0);
insert into computers values (119,'cray j90', 0);
insert into computers values (120,'cray xt3', 0);
insert into computers values (121,'cray cs6400', 0);
insert into computers values (122,'atari st', 20);
insert into computers values (123,'amiga 2500', 0);
insert into computers values (124,'amiga 2500', 6);
insert into computers values (125,'amiga 4000', 6);
insert into computers values (126,'amiga 3000ux', 6);
insert into computers values (127,'amiga 3000t', 6);
insert into computers values (128,'amiga 4000t', 6);
insert into computers values (129,'amiga 1200', 6);
insert into computers values (130,'atari 1040 stf', 0);
insert into computers values (131,'atari 520 st', 0);
insert into computers values (132,'atari 520 stfm', 0);
insert into computers values (133,'atari 1040 ste', 0);
insert into computers values (134,'atari mega ste', 0);
insert into computers values (135,'atari 520 st+', 0);
insert into computers values (136,'atari 520 stm', 0);
insert into computers values (137,'atari 130 st', 0);
insert into computers values (138,'atari 260 st', 0);
insert into computers values (139,'atari mega st', 0);
insert into computers values (140,'atari 520 stf', 0);
insert into computers values (141,'atari 1040 stfm', 0);
insert into computers values (142,'atari 2080 st', 0);
insert into computers values (143,'atari 260 st+', 0);
insert into computers values (144,'atari 4160 ste', 0);
insert into computers values (145,'trs-80 color computersrow 2', 0);
insert into computers values (146,'trs-80 color computersrow 3', 0);
insert into computers values (147,'trs-80 model 1', 5);
insert into computers values (148,'timex sinclair 2068', 23);
insert into computers values (149,'zx spectrum', 25);
insert into computers values (150,'xerox star', 26);
insert into computers values (151,'xerox alto', 0);
insert into computers values (152,'acorn archimedes', 22);
insert into computers values (153,'nintendo entertainment system', 24);
insert into computers values (154,'super nintendo entertainment system', 24);
insert into computers values (155,'super famicom', 0);
insert into computers values (156,'nintendo gamecube', 24);
insert into computers values (157,'game boy line', 0);
insert into computers values (158,'playstation', 17);
insert into computers values (159,'playstation 2', 17);
insert into computers values (160,'game & watch', 24);
insert into computers values (161,'edsac', 0);
insert into computers values (162,'ibm system/4 pi', 0);
insert into computers values (163,'ibm ap-101', 0);
insert into computers values (164,'ibm tc-1', 0);
insert into computers values (165,'ibm ap-101b', 0);
insert into computers values (166,'ibm ap-101s', 13);
insert into computers values (167,'proliant', 27);
insert into computers values (168,'http://nepomuk.semanticdesktop.org/xwiki/', 0);
insert into computers values (169,'sinclair ql', 25);
insert into computers values (170,'sinclair zx81', 25);
insert into computers values (171,'sinclair zx80', 25);
insert into computers values (172,'atari 65xe', 20);
insert into computers values (173,'deep blue', 0);
insert into computers values (174,'macintosh quadra 650', 0);
insert into computers values (175,'macintosh quadra 610', 0);
insert into computers values (176,'macintosh quadra 800', 0);
insert into computers values (177,'macintosh quadra 950', 0);
insert into computers values (178,'powerbook 160', 0);
insert into computers values (179,'powerbook 145b', 0);
insert into computers values (180,'powerbook 170', 0);
insert into computers values (181,'powerbook 145', 0);
insert into computers values (182,'powerbook g3', 0);
insert into computers values (183,'powerbook 140', 0);
insert into computers values (184,'macintosh iicx', 0);
insert into computers values (185,'powerbook 180', 0);
insert into computers values (186,'powerbook g4', 0);
insert into computers values (187,'macintosh xl', 0);
insert into computers values (188,'powerbook 100', 0);
insert into computers values (189,'powerbook 2400c', 0);
insert into computers values (190,'powerbook 1400', 0);
insert into computers values (191,'macintosh quadra 630', 0);
insert into computers values (192,'macintosh quadra 660av', 0);
insert into computers values (193,'macintosh quadra 840av', 0);
insert into computers values (194,'powerbook 5300', 0);
insert into computers values (195,'powerbook 3400c', 0);
insert into computers values (196,'macintosh color classic', 0);
insert into computers values (197,'macintosh 512ke', 0);
insert into computers values (198,'macintosh iisi', 0);
insert into computers values (199,'macintosh iix', 0);
insert into computers values (200,'powerbook 500 series', 0);
insert into computers values (201,'power macintosh g3', 0);
insert into computers values (202,'macintosh iici', 0);
insert into computers values (203,'imac g5', 1);
insert into computers values (204,'power mac g4', 0);
insert into computers values (205,'power macintosh 7100', 0);
insert into computers values (206,'power macintosh 9600', 0);
insert into computers values (207,'power macintosh 7200', 0);
insert into computers values (208,'power macintosh 7300', 0);
insert into computers values (209,'power macintosh 8600', 0);
insert into computers values (210,'power macintosh 6200', 0);
insert into computers values (211,'power macintosh 8100', 0);
insert into computers values (212,'compact macintosh', 0);
insert into computers values (213,'power macintosh 4400', 0);
insert into computers values (214,'power macintosh 9500', 0);
insert into computers values (215,'macintosh portable', 0);
insert into computers values (216,'emac', 0);
insert into computers values (217,'power macintosh 7600', 0);
insert into computers values (218,'power mac g5', 0);
insert into computers values (219,'power macintosh 7500', 0);
insert into computers values (220,'power macintosh 6100', 0);
insert into computers values (221,'power macintosh 8500', 0);
insert into computers values (222,'macintosh iivi', 0);
insert into computers values (223,'macintosh iivx', 0);
insert into computers values (224,'imac g3', 0);
insert into computers values (225,'imac g4', 0);
insert into computers values (226,'power mac g4 cube', 1);
insert into computers values (227,'intel imac', 0);
insert into computers values (228,'deep thought', 13);
insert into computers values (229,'wii', 24);
insert into computers values (230,'ibm system x', 0);
insert into computers values (231,'ibm system i', 13);
insert into computers values (232,'ibm system z', 13);
insert into computers values (233,'ibm system p', 13);
insert into computers values (234,'lc 575', 0);
insert into computers values (235,'macintosh tv', 0);
insert into computers values (236,'macintosh performa', 0);
insert into computers values (237,'macintosh ii series', 0);
insert into computers values (238,'power macintosh 6400', 0);
insert into computers values (239,'power macintosh 6500', 0);
insert into computers values (240,'apple penlite', 0);
insert into computers values (241,'wallstreet', 0);
insert into computers values (242,'twentieth anniversary macintosh', 0);
insert into computers values (243,'power macintosh 5500', 0);
insert into computers values (244,'ibook g3', 1);
insert into computers values (245,'power macintosh 5200 lc', 0);
insert into computers values (246,'power macintosh 5400', 0);
insert into computers values (247,'cm-1', 0);
insert into computers values (248,'msx', 28);
insert into computers values (249,'playstation 3', 17);
insert into computers values (250,'msx2', 29);
insert into computers values (251,'msx2+', 30);
insert into computers values (252,'msx turbo r', 0);
insert into computers values (253,'panasonic fs a1gt', 0);
insert into computers values (254,'panasonic fs a1st', 0);
insert into computers values (255,'pdp-11', 10);
insert into computers values (256,'pdp-1', 10);
insert into computers values (257,'pdp-10', 10);
insert into computers values (258,'pdp-8', 10);
insert into computers values (259,'pdp-6', 10);
insert into computers values (260,'decsystem-20', 10);
insert into computers values (261,'pdp-7', 10);
insert into computers values (262,'pdp-5', 10);
insert into computers values (263,'pdp-12', 10);
insert into computers values (264,'linc', 10);
insert into computers values (265,'pdp-14', 10);
insert into computers values (266,'pdp-15', 10);
insert into computers values (267,'pdp-16', 10);
insert into computers values (268,'cray x2', 31);
insert into computers values (269,'cray x-mp', 31);
insert into computers values (270,'evans & sutherland es-1', 32);
insert into computers values (271,'commodore vic-20', 6);
insert into computers values (272,'powerbook 150', 0);
insert into computers values (273,'macbook air', 1);
insert into computers values (274,'digi-comp i', 33);
insert into computers values (275,'digi-comp', 0);
insert into computers values (276,'digi-comp ii', 33);
insert into computers values (277,'manchester mark i', 0);
insert into computers values (278,'small-scale experimental machine', 0);
insert into computers values (279,'nintendo 64', 24);
insert into computers values (280,'game boy advance', 24);
insert into computers values (281,'game boy', 24);
insert into computers values (282,'nintendo ds lite', 24);
insert into computers values (283,'nintendo ds', 24);
insert into computers values (284,'game boy color', 24);
insert into computers values (285,'game boy advance sp', 24);
insert into computers values (286,'virtual boy', 24);
insert into computers values (287,'game boy micro', 24);
insert into computers values (288,'roadrunner', 13);
insert into computers values (289,'hp 9000', 0);
insert into computers values (290,'omron luna-88k2', 0);
insert into computers values (291,'omron luna-88k', 34);
insert into computers values (292,'motorola series 900', 0);
insert into computers values (293,'motorola m8120', 0);
insert into computers values (294,'triton dolphin system 100', 0);
insert into computers values (295,'bbn tc2000', 35);
insert into computers values (296,'wrt54g', 0);
insert into computers values (297,'thinkpad', 36);
insert into computers values (298,'apple newton', 1);
insert into computers values (299,'atanasoff-berry computersrow', 0);
insert into computers values (300,'atlas computersrow', 0);
insert into computers values (301,'asus eee pc 901', 37);
insert into computers values (302,'asus eee pc 701', 0);
insert into computers values (303,'ibm 7030', 13);
insert into computers values (304,'system/38', 13);
insert into computers values (305,'system/36', 13);
insert into computers values (306,'ibm 7090', 13);
insert into computers values (307,'ibm rt', 13);
insert into computers values (308,'system/360', 13);
insert into computers values (309,'ibm 801', 13);
insert into computers values (310,'ibm 1401', 13);
insert into computers values (311,'asci white', 13);
insert into computers values (312,'blue gene', 13);
insert into computers values (313,'asci blue pacific', 13);
insert into computers values (314,'iphone', 1);
insert into computers values (315,'nokia n810', 16);
insert into computers values (316,'edsac 2', 0);
insert into computers values (317,'titan', 0);
insert into computers values (318,'pilot ace', 0);
insert into computers values (319,'hp mini 1000', 27);
insert into computers values (320,'hp 2133 mini-note pc', 27);
insert into computers values (321,'kogan agora pro', 0);
insert into computers values (322,'d-series machines', 0);
insert into computers values (323,'zx spectrum 48k', 25);
insert into computers values (324,'zx spectrum 16k', 25);
insert into computers values (325,'zx spectrum 128', 25);
insert into computers values (326,'zx spectrum +3', 38);
insert into computers values (327,'zx spectrum +2', 38);
insert into computers values (328,'zx spectrum +2a', 38);
insert into computers values (329,'zx spectrum +', 25);
insert into computers values (330,'acer extensa', 0);
insert into computers values (331,'acer extensa 5220', 0);
insert into computers values (332,'dell latitude', 0);
insert into computers values (333,'toshiba satellite', 0);
insert into computers values (334,'timex sinclair 2048', 23);
insert into computers values (335,'sprinter', 0);
insert into computers values (336,'timex computersrow 2048', 0);
insert into computers values (337,'pentagon', 0);
insert into computers values (338,'belle', 0);
insert into computers values (339,'loki', 25);
insert into computers values (340,'hobbit', 0);
insert into computers values (341,'next computersrow', 19);
insert into computers values (342,'trs-80', 0);
insert into computers values (343,'trs-80 model 2', 5);
insert into computers values (344,'trs-80 model 3', 5);
insert into computers values (345,'stacy', 0);
insert into computers values (346,'st book', 0);
insert into computers values (347,'atari 520 ste', 0);
insert into computers values (348,'amiga 2000 model a', 0);
insert into computers values (349,'amiga 2000 model b', 0);
insert into computers values (350,'amiga 2000 model c', 0);
insert into computers values (351,'ibm 3270', 0);
insert into computers values (352,'caldic', 0);
insert into computers values (353,'modbook', 0);
insert into computers values (354,'compaq systempro', 0);
insert into computers values (355,'arra', 0);
insert into computers values (356,'ibm system cluster 1350', 0);
insert into computers values (357,'finite element machine', 0);
insert into computers values (358,'es7000', 0);
insert into computers values (359,'hp mediasmart server', 0);
insert into computers values (360,'hp superdome', 0);
insert into computers values (361,'ibm power systems', 13);
insert into computers values (362,'oslo analyzer', 0);
insert into computers values (363,'microsoft softcard', 0);
insert into computers values (364,'witch', 0);
insert into computers values (365,'analytical engine', 0);
insert into computers values (366,'edvac', 0);
insert into computers values (367,'binac', 0);
insert into computers values (368,'earth simulator', 0);
insert into computers values (369,'bark', 0);
insert into computers values (370,'harvard mark i', 13);
insert into computers values (371,'illiac iv', 0);
insert into computers values (372,'illiac ii', 0);
insert into computers values (373,'illiac iii', 0);
insert into computers values (374,'water integrator', 0);
insert into computers values (375,'csirac', 0);
insert into computers values (376,'system x', 0);
insert into computers values (377,'harvest', 0);
insert into computers values (378,'chiptest', 0);
insert into computers values (379,'hitech', 0);
insert into computers values (380,'bomba', 0);
insert into computers values (381,'ace', 0);
insert into computers values (382,'asci red', 0);
insert into computers values (383,'asci thors hammer', 0);
insert into computers values (384,'asci purple', 13);
insert into computers values (385,'asci blue mountain', 0);
insert into computers values (386,'columbia', 0);
insert into computers values (387,'hp integrity', 0);
insert into computers values (388,'apexc', 0);
insert into computers values (389,'datasaab d2', 0);
insert into computers values (390,'brlesc', 0);
insert into computers values (391,'dyseac', 0);
insert into computers values (392,'ssec', 13);
insert into computers values (393,'hydra', 0);
insert into computers values (394,'fujic', 0);
insert into computers values (395,'raydac', 0);
insert into computers values (396,'harvard mark iii', 0);
insert into computers values (397,'datar', 0);
insert into computers values (398,'reservec', 0);
insert into computers values (399,'dask', 0);
insert into computers values (400,'utec', 0);
insert into computers values (401,'drte computersrow', 0);
insert into computers values (402,'poweredge', 0);
insert into computers values (403,'apple network server', 0);
insert into computers values (404,'goodyear mpp', 0);
insert into computers values (405,'macintosh 128k technical details', 0);
insert into computers values (406,'power macintosh g3', 0);
insert into computers values (407,'cer-10', 0);
insert into computers values (408,'cer-20', 0);
insert into computers values (409,'ibm bladecenter', 13);
insert into computers values (410,'wisconsin integrally synchronized computersrow', 0);
insert into computers values (411,'amstrad cpc', 38);
insert into computers values (412,'amstrad cpc 6128', 38);
insert into computers values (413,'amstrad cpc 664', 38);
insert into computers values (414,'amstrad cpc 464', 38);
insert into computers values (415,'intergraph', 0);
insert into computers values (416,'enterprise', 0);
insert into computers values (417,'mtx500', 0);
insert into computers values (418,'acorn electron', 0);
insert into computers values (419,'sony vaio p', 17);
insert into computers values (420,'vaio', 17);
insert into computers values (421,'sony vaio p vgn-p588e/q', 0);
insert into computers values (422,'sony vaio p vgn-p530h/g', 0);
insert into computers values (423,'sony vaio p vgn-p530h/w', 0);
insert into computers values (424,'sony vaio p vgn-p530h/q', 0);
insert into computers values (425,'sony vaio p vgn-p530h/r', 0);
insert into computers values (426,'sony vaio p vgn-p588e/r', 0);
insert into computers values (427,'sony vaio p vgn-p598e/q', 0);
insert into computers values (428,'timex sinclair 1000', 23);
insert into computers values (429,'komputer 2086', 0);
insert into computers values (430,'galaksija', 0);
insert into computers values (431,'vector-06c', 0);
insert into computers values (432,'elektronika bk', 0);
insert into computers values (433,'sun386i', 39);
insert into computers values (434,'xerox daybreak', 0);
insert into computers values (435,'xerox notetaker', 26);
insert into computers values (436,'d4a', 0);
insert into computers values (437,'lgp-30', 0);
insert into computers values (438,'lgp-21', 0);
insert into computers values (439,'asus eee pc 900', 37);
insert into computers values (440,'atari tt030', 0);
insert into computers values (441,'bi am zx-spectrum 48/64', 0);
insert into computers values (442,'bi am zx-spectrum 128', 0);
insert into computers values (443,'playstation portable', 0);
insert into computers values (444,'msi wind netbook', 0);
insert into computers values (445,'sharp mebius nj70a', 0);
insert into computers values (446,'htc snap', 41);
insert into computers values (447,'commodore educator 64', 6);
insert into computers values (448,'amiga 1500', 6);
insert into computers values (449,'commodore 65', 6);
insert into computers values (450,'commodore 16', 6);
insert into computers values (451,'commodore cbm-ii', 6);
insert into computers values (452,'commodore plus/4', 6);
insert into computers values (453,'commodore lcd', 6);
insert into computers values (454,'commodore max machine', 6);
insert into computers values (455,'aster ct-80', 0);
insert into computers values (456,'test', 0);
insert into computers values (457,'msi gx723', 0);
insert into computers values (458,'eee pc 1000hv', 0);
insert into computers values (459,'vtech laser 200', 0);
insert into computers values (460,'crunchpad', 0);
insert into computers values (461,'neo geo', 0);
insert into computers values (462,'sega mega drive', 0);
insert into computers values (463,'sega master system', 0);
insert into computers values (464,'turbografx-16', 0);
insert into computers values (465,'sun-3', 39);
insert into computers values (466,'pleiades', 0);
insert into computers values (467,'ibm sequoia', 0);
insert into computers values (468,'inves spectrum 48k plus', 0);
insert into computers values (469,'iphone 3g', 0);
insert into computers values (470,'iphone 3gs', 0);
insert into computers values (471,'beagle board', 40);
insert into computers values (472,'hp npar', 0);
insert into computers values (473,'macbook family', 0);
insert into computers values (474,'reservisor', 0);
insert into computers values (475,'bladesystem', 0);
insert into computers values (476,'lenovo thinkpad t60p', 0);
insert into computers values (477,'lenovo thinkpad x200', 36);
insert into computers values (478,'lenovo thinkpad t60', 0);
insert into computers values (479,'lenovo thinkpad w700', 0);
insert into computers values (480,'lenovo thinkpad t41', 0);
insert into computers values (481,'lenovo thinkpad z61p', 0);
insert into computers values (482,'lenovo thinkpad x61s', 0);
insert into computers values (483,'lenovo thinkpad t43', 0);
insert into computers values (484,'lenovo thinkpad r400', 0);
insert into computers values (485,'lenovo thinkpad x60s', 0);
insert into computers values (486,'lenovo thinkpad x301', 0);
insert into computers values (487,'lenovo thinkpad t42', 0);
insert into computers values (488,'lenovo thinkpad r61', 0);
insert into computers values (489,'lenovo thinkpad w500', 0);
insert into computers values (490,'lenovo thinkpad sl400', 0);
insert into computers values (491,'lenovo thinkpad x40', 0);
insert into computers values (492,'lenovo thinkpad x200 tablet', 36);
insert into computers values (493,'lenovo thinkpad t400s', 0);
insert into computers values (494,'nokia n900', 16);
insert into computers values (495,'internet tablet', 0);
insert into computers values (496,'meiko computing surface', 0);
insert into computers values (497,'cs-2', 0);
insert into computers values (498,'ibm 701', 13);
insert into computers values (499,'ibm 5100', 13);
insert into computers values (500,'an/fsq-7', 13);
insert into computers values (501,'an/fsq-32', 13);
insert into computers values (502,'ibm cpc', 13);
insert into computers values (503,'system/34', 13);
insert into computers values (504,'system/32', 13);
insert into computers values (505,'system/3', 13);
insert into computers values (506,'ibm 305', 13);
insert into computers values (507,'english electric deuce', 0);
insert into computers values (508,'cer-203', 0);
insert into computers values (509,'cer-22', 0);
insert into computers values (510,'kentucky linux athlon testbed', 0);
insert into computers values (511,'qnap ts-101', 0);
insert into computers values (512,'ipad', 1);
insert into computers values (513,'iphone 2g', 0);
insert into computers values (514,'inslaw', 0);
insert into computers values (515,'wepad', 0);
insert into computers values (516,'macbook parts', 1);
insert into computers values (517,'macbook 13-inch core 2 duo 2.13ghz (mc240ll/a) ddr2 model', 1);
insert into computers values (518,'macbook 13-inch core 2 duo 2.13ghz (mc240t/a) ddr2 model', 0);
insert into computers values (519,'macbook 13-inch core 2 duo 2.13ghz (mc240x/a) ddr2 model', 0);
insert into computers values (520,'macbook 13-inch core 2 duo 2.26ghz (unibody mc207ll/a) ddr3 model', 0);
insert into computers values (521,'mc240ll/a', 0);
insert into computers values (522,'d.k.communication', 0);
insert into computers values (523,'iphone 4', 1);
insert into computers values (524,'nintendo 3ds', 24);
insert into computers values (525,'asus eee pc 1005pe', 37);
insert into computers values (526,'national law enforcement system', 0);
insert into computers values (527,'blackberry playbook', 42);
insert into computers values (528,'barnes & noble nook', 0);
insert into computers values (529,'sam coupé', 0);
insert into computers values (530,'htc dream', 41);
insert into computers values (531,'samsung galaxy tab', 43);
insert into computers values (532,'blackberry playbook', 42);
insert into computers values (533,'tianhe-i', 0);
insert into computers values (534,'kno', 0);
insert into computers values (535,'thinkpad 701 c', 0);
insert into computers values (536,'thinkpad 340 cse', 0);
insert into computers values (537,'thinkpad 755 cx', 0);
insert into computers values (538,'thinkpad 755 ce', 0);
insert into computers values (539,'thinkpad 370 c', 0);
insert into computers values (540,'coleco adam', 0);
insert into computers values (541,'nebulae', 0);
insert into computers values (542,'alex ereader', 0);
insert into computers values (543,'acer iconia', 0);
insert into computers values (544,'archos 101', 0);
insert into computers values (545,'fujitsu lifebook t900', 0);
insert into computers values (546,'motorola xoom', 0);
insert into computers values (547,'viewsonic g tablet', 0);
insert into computers values (548,'dec professional', 10);
insert into computers values (549,'dec multia', 10);
insert into computers values (550,'dec firefly', 10);
insert into computers values (551,'dec 3000 axp', 10);
insert into computers values (552,'dec 2000 axp', 10);
insert into computers values (553,'dec 4000 axp', 10);
insert into computers values (554,'dec 7000/10000 axp', 10);
insert into computers values (555,'dec professional 350', 0);
insert into computers values (556,'dec rainbow 100', 0);
insert into computers values (557,'dec professional 325', 0);
insert into computers values (558,'decmate ii', 10);
insert into computers values (559,'decmate', 10);
insert into computers values (560,'decsystem', 10);
insert into computers values (561,'netapp filer', 0);
insert into computers values (562,'dec gt40', 10);
insert into computers values (563,'ecoatm', 0);
insert into computers values (564,'mindwave braincubed education bundle', 0);
insert into computers values (565,'palmpilot', 0);
insert into computers values (566,'upcoming iphone 5', 1);
insert into computers values (567,'dell inspiron 560 desktop computersrow ', 0);
insert into computers values (568,'ipad 2', 1);
insert into computers values (569,'hp touchpad', 27);
insert into computers values (570,'hp veer', 27);
insert into computers values (571,'lenovo thinkpad edge 11', 36);
insert into computers values (572,'dell vostro', 0);
insert into computers values (573,'gateway lt3103u', 0);
insert into computers values (574,'iPhone 4S', 1);

# --- !Downs
drop table companies;
drop table computers;
